<?php

/**
 * BaseAlergia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property BIGINT $mascota_id
 * @property string $alergia
 * @property Mascota $Mascota
 * 
 * @method BIGINT  getMascotaId()  Returns the current record's "mascota_id" value
 * @method string  getAlergia()    Returns the current record's "alergia" value
 * @method Mascota getMascota()    Returns the current record's "Mascota" value
 * @method Alergia setMascotaId()  Sets the current record's "mascota_id" value
 * @method Alergia setAlergia()    Sets the current record's "alergia" value
 * @method Alergia setMascota()    Sets the current record's "Mascota" value
 * 
 * @package    pethealth
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlergia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('alergia');
        $this->hasColumn('mascota_id', 'BIGINT', null, array(
             'type' => 'BIGINT',
             'notnull' => true,
             ));
        $this->hasColumn('alergia', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mascota', array(
             'local' => 'mascota_id',
             'foreign' => 'id',
             'onDelete' => 'Cascade'));
    }
}