<?php

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $email
 * @property string $usuario
 * @property string $password
 * @property string $version
 * @property boolean $mailing
 * @property string $idioma
 * @property Doctrine_Collection $Mascota
 * 
 * @method string              getNombre()   Returns the current record's "nombre" value
 * @method string              getEmail()    Returns the current record's "email" value
 * @method string              getUsuario()  Returns the current record's "usuario" value
 * @method string              getPassword() Returns the current record's "password" value
 * @method string              getVersion()  Returns the current record's "version" value
 * @method boolean             getMailing()  Returns the current record's "mailing" value
 * @method string              getIdioma()   Returns the current record's "idioma" value
 * @method Doctrine_Collection getMascota()  Returns the current record's "Mascota" collection
 * @method Usuario             setNombre()   Sets the current record's "nombre" value
 * @method Usuario             setEmail()    Sets the current record's "email" value
 * @method Usuario             setUsuario()  Sets the current record's "usuario" value
 * @method Usuario             setPassword() Sets the current record's "password" value
 * @method Usuario             setVersion()  Sets the current record's "version" value
 * @method Usuario             setMailing()  Sets the current record's "mailing" value
 * @method Usuario             setIdioma()   Sets the current record's "idioma" value
 * @method Usuario             setMascota()  Sets the current record's "Mascota" collection
 * 
 * @package    pethealth
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('usuario', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('password', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 40,
             ));
        $this->hasColumn('version', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('mailing', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('idioma', 'string', 15, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Mascota', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));
    }
}