<?php

/**
 * BaseMascota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property BIGINT $usuario_id
 * @property string $nombre
 * @property date $fechaNacimiento
 * @property string $especie
 * @property string $raza
 * @property int $tamano
 * @property int $sexo
 * @property Usuario $Usuario
 * @property Doctrine_Collection $Vacuna
 * @property Doctrine_Collection $Alergia
 * @property Doctrine_Collection $Enfermedad
 * 
 * @method BIGINT              getUsuarioId()       Returns the current record's "usuario_id" value
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method date                getFechaNacimiento() Returns the current record's "fechaNacimiento" value
 * @method string              getEspecie()         Returns the current record's "especie" value
 * @method string              getRaza()            Returns the current record's "raza" value
 * @method int                 getTamano()          Returns the current record's "tamano" value
 * @method int                 getSexo()            Returns the current record's "sexo" value
 * @method Usuario             getUsuario()         Returns the current record's "Usuario" value
 * @method Doctrine_Collection getVacuna()          Returns the current record's "Vacuna" collection
 * @method Doctrine_Collection getAlergia()         Returns the current record's "Alergia" collection
 * @method Doctrine_Collection getEnfermedad()      Returns the current record's "Enfermedad" collection
 * @method Mascota             setUsuarioId()       Sets the current record's "usuario_id" value
 * @method Mascota             setNombre()          Sets the current record's "nombre" value
 * @method Mascota             setFechaNacimiento() Sets the current record's "fechaNacimiento" value
 * @method Mascota             setEspecie()         Sets the current record's "especie" value
 * @method Mascota             setRaza()            Sets the current record's "raza" value
 * @method Mascota             setTamano()          Sets the current record's "tamano" value
 * @method Mascota             setSexo()            Sets the current record's "sexo" value
 * @method Mascota             setUsuario()         Sets the current record's "Usuario" value
 * @method Mascota             setVacuna()          Sets the current record's "Vacuna" collection
 * @method Mascota             setAlergia()         Sets the current record's "Alergia" collection
 * @method Mascota             setEnfermedad()      Sets the current record's "Enfermedad" collection
 * 
 * @package    pethealth
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMascota extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mascota');
        $this->hasColumn('usuario_id', 'BIGINT', null, array(
             'type' => 'BIGINT',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('fechaNacimiento', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('especie', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('raza', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('tamano', 'int', 1, array(
             'type' => 'int',
             'notnull' => false,
             'length' => 1,
             ));
        $this->hasColumn('sexo', 'int', 1, array(
             'type' => 'int',
             'notnull' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'Cascade'));

        $this->hasMany('Vacuna', array(
             'local' => 'id',
             'foreign' => 'mascota_id'));

        $this->hasMany('Alergia', array(
             'local' => 'id',
             'foreign' => 'mascota_id'));

        $this->hasMany('Enfermedad', array(
             'local' => 'id',
             'foreign' => 'mascota_id'));
    }
}