<?php

/**
 * BaseVacuna
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property BIGINT $mascota_id
 * @property string $vacuna
 * @property date $fechaAplicacion
 * @property Mascota $Mascota
 * 
 * @method BIGINT  getMascotaId()       Returns the current record's "mascota_id" value
 * @method string  getVacuna()          Returns the current record's "vacuna" value
 * @method date    getFechaAplicacion() Returns the current record's "fechaAplicacion" value
 * @method Mascota getMascota()         Returns the current record's "Mascota" value
 * @method Vacuna  setMascotaId()       Sets the current record's "mascota_id" value
 * @method Vacuna  setVacuna()          Sets the current record's "vacuna" value
 * @method Vacuna  setFechaAplicacion() Sets the current record's "fechaAplicacion" value
 * @method Vacuna  setMascota()         Sets the current record's "Mascota" value
 * 
 * @package    pethealth
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVacuna extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vacuna');
        $this->hasColumn('mascota_id', 'BIGINT', null, array(
             'type' => 'BIGINT',
             'notnull' => true,
             ));
        $this->hasColumn('vacuna', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('fechaAplicacion', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mascota', array(
             'local' => 'mascota_id',
             'foreign' => 'id',
             'onDelete' => 'Cascade'));
    }
}