<?php

/**
 * BaseEnfermedad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property BIGINT $mascota_id
 * @property string $enfermedad
 * @property string $tratamiento
 * @property date $fecha
 * @property Mascota $Mascota
 * 
 * @method BIGINT     getMascotaId()   Returns the current record's "mascota_id" value
 * @method string     getEnfermedad()  Returns the current record's "enfermedad" value
 * @method string     getTratamiento() Returns the current record's "tratamiento" value
 * @method date       getFecha()       Returns the current record's "fecha" value
 * @method Mascota    getMascota()     Returns the current record's "Mascota" value
 * @method Enfermedad setMascotaId()   Sets the current record's "mascota_id" value
 * @method Enfermedad setEnfermedad()  Sets the current record's "enfermedad" value
 * @method Enfermedad setTratamiento() Sets the current record's "tratamiento" value
 * @method Enfermedad setFecha()       Sets the current record's "fecha" value
 * @method Enfermedad setMascota()     Sets the current record's "Mascota" value
 * 
 * @package    pethealth
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEnfermedad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('enfermedad');
        $this->hasColumn('mascota_id', 'BIGINT', null, array(
             'type' => 'BIGINT',
             'notnull' => true,
             ));
        $this->hasColumn('enfermedad', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('tratamiento', 'string', 500, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 500,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mascota', array(
             'local' => 'mascota_id',
             'foreign' => 'id',
             'onDelete' => 'Cascade'));
    }
}