<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/05/13 18:09:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=petshealth',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
