<?php

/**
 * AlergiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlergiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlergiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Alergia');
    }
}