<?php

/**
 * VacunaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VacunaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VacunaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Vacuna');
    }
}